theme: jekyll-theme-minimal
title: Cheryl Flynn Brooks
author: Cheryl Flynn Brooks
avatar: https://avatars3.githubusercontent.com/u/1244948?s=460&u=2983c40d033f18ee0ffc2331be0e625819b1704c&v=4

social-network-links:
  email: flynn.cheryl@gmail.com
  linkedin: https://www.linkedin.com/in/cheryl-flynn-brooks/
